---
title: "Values, Education, and Religiosity among Muslims"
author:
- affiliation: University of Oregon, Sociology
  name: Aaron Gullickson
- affiliation: University of Oregon, Sociology
  name: Sarah Ahmed
keywords: keywords
#FYI: the thanks and abstract are easier to view and edit in Atom which does proper linewrapping
thanks: Thanks to people and stuff
abstract: This is a test abstract
output:
  pdf_document:
    citation_package: natbib
    fig_caption: yes
    template: ./resources/aog-latex-ms.tex
  word_document:
    reference_docx: ./resources/aog_word_style.docx
fontfamily: mathpazo
fontsize: 11pt
anonymous: false #anonymize, double-space, and ragged right
endnotes: false #make footnotes endnotes
endfloat: false #move table and figures to the end
bibliography: ../project.bib
biblio-style: ./resources/ajs.bst
---

# Introduction

In a viral appearance on the HBO Show “Real Time with Bill Maher” in 2014, actor Ben Affleck became embroiled in an unexpected debate with host Bill Maher and fellow guest, Sam Harris, over the allegedly authoritarian and violent tendencies of Islamic doctrine. Harris, one of the leading figures in the New Atheist movement, argued that Islam "at this moment is the motherlode of bad ideas." To support this view, Maher offered data from a recent poll of Muslims worldwide conducted by the Pew Research Center which showed that  "like 90%" of Egyptian Muslims supported death as a punishment for leaving the faith.

Although Maher’s figure was factually correct, the statistic is nonetheless misleading.^[Some initial media reports incorrectly claimed that the percentage was 64%, but the correct value from the Pew report and our own analysis below show the percentage to be 88%]. Egyptian Muslims were more supportive of this statement than Muslims in any other country in the Pew study. In contrast, only 0.8% of Muslims in Kazakhstan felt similarly. Among the more than thirty countries in the cited Pew survey as well as a similar one conducted in sub-Saharan Africa, the level of support among Muslims  for killing apostates varies uniformly between these two extremes. These studies reveals that extreme variation rather than strict orthodoxy is the key to understanding Muslim responses to this question. For social scientists, this variation then begs a further question - why do Muslims vary so much in their support for such “bad” ideas?

In this article, we take up this question with a more formal analysis of the Pew data. The data were collected on Muslims in thirty-five countries representing roughly sixty-five percent of the global Muslim population between 2008-12. From this data, we develop a value construct measuring support for violent practices from three questions on the acceptability of killing apostates, the stoning of adulterers, and severe corporal punishment for thieves. Following the work on modernization and development, our analysis focuses on the relationship between these values, education, religiosity, and development. 

Our analysis builds on a long tradition of research on value systems in Muslim populations, and complements prior research in several important ways. First, we address specific attitudes that are rarely examined in scholarly work, despite their prominence in popular discussions of Islam in the West. This gap in the existing research is largely driven by data limitations. Most research is conducted on datasets using large cross-national samples, such as the World Values Survey. In order to enable comparisons, individuals in such samples are asked questions that are likely to be understood by most survey respondents. For this reason, much of the research focuses on universalistic attitudes around abstract concepts of human rights, democracy, and women’s rights, or relies on large aggregate indices of value systems that are driven by a multitude of specific attitudes ranging from acceptance of abortion to whether respondents would be willing to sign a petition (Inglehardt). 

The shortcoming of focusing on universalistic attitudes is that they give us little insight into the specific attitudes and values that differentiate cultural and religious groups. For example, whether a respondent is willing to sign a petition or is supportive of democracy in the abstract may tell us little to nothing about how that respondent feels toward the mandate that apostates should be killed. Yet, the justifiability of killing apostates is a topic that both divides Muslims internally and distinguishes Muslims from other religious groups. It is not simply that Muslims feel differently on this issue in comparison to other religious groups, but rather that the question itself is only intelligible among Muslims. 

Second, the large sample of countries here allows us to more systematically examine country-level variation than has been possible in most studies of value systems in Muslim populations. Importantly, we examine not only heterogeneity in the overall support for violent practices, but heterogeneity in the relationship of education and religiosity to this support. 

While classic modernization theory expected a fairly uniform pattern of modernization, contemporary scholars expect greater heterogeneity in this process. Some have even suggested that change in cultural systems (including values and attitudes) may be largely unconnected to processes of modernization and development. Using multilevel models, we explore this heterogeneity. We pay particular attention to the relationships between overall level of support and the two key associations with education and religiosity. We argue that the patterns of these relationships at the country-level give us some insight into how educational and religious institutions are implicated in the process of value change at the country level. 

==TODO: OUR FINDINGS==

# Values, Education, and Religiosity

Education and religiosity are often treated as key variables in processes of modernization and value change because of their connection to classic modernization theory and the closely related secularization theory. Classic modernization theory treats cultural and value change as largely a by-product of structural development [@lerner_passing_1958; @parsons_social_1964; @inkeles_becoming_1974]. Industrialization and economic growth bring about greater differentiation in the occupational workforce, urbanization, and higher standards of living [@rostow_stages_1960]. All of these factors contribute to a shift from traditional and authoritarian values to liberal values that promote individual autonomy and self-determination [@parsons_social_1964]. Concomitantly, rationalization and the decline of traditional values reduce the significance of religious institutions in favor of secular institutions, diminishing the role of religion in social life [@wilson_religion_1966; @bruce_secularization:_2011].

Modernization scholars often treat education as a crucial fulcrum at the individual level for these processes of modernization [@meyer_effects_1977; @chabbott_development_2000; @depaepe_educationalization_2008]. As a form of capital investment, educational expansion and growth is tied strongly to modernization due to its role in economic growth and occupational differentiation. This can be seen in the examples of development policies and goals initiated and funded by the World Bank, IMF, etc as a move to make societies more progressive. Examples include the harvard advisory council in pakistan and even policies undertaken during the kemalism era in Turkey. Education may also be linked to more fundamental cognitive changes in the way people view the world [@adorno_authoritarian_1950; @mcclosky_dimensions_1983].

Numerous studies in mostly Western countries have found that education is positively related to liberal values, often defined in terms of tolerance for pluralism [@hyman_educations_1979; @bobo_education_1989; @weakliem_effects_2002; @kingston_why_2003]. While these results are consistent with modernization theory, other scholars argue for a different understanding of this relationship. In particular, the socialization school of thought argues that education tends to socialize individuals to the prevailing norms of a society [@selznick_tenacity_1969; @jackman_education_1984]. Therefore, the liberalizing effects of education will only exist in countries where liberal values are commonplace. Cross-national results in Western countries show that the positive effect of education is greatest in countries with more liberal values overall, consistent with the socialization perspective [@weil_variable_1985]. 

Some studies hold religiosity as the anti-modern counterweight to education in that high levels of religiosity indicate commitments to traditional and authoritarian values [@rokeach_part_1969; @rokeach_part_1969-1; @wilcox_evangelicals_1990, p. 27]. Although there is significant heterogeneity across countries, research has shown that religious identification tends to be associated with support for right-wing parties and lower levels of tolerance for outgroups [@wilcox_evangelicals_1990; @kelley_class_1995; @karpov_religiosity_2002; @norris_sacred_2011, pp. 201-212].

A key concern in such studies, however, is the definition of religiosity. Given that the core religious texts of the major Western religions are frequently traditional and authoritarian, it is not surprising that strong believers with a tendency for theological literalism would themselves be more traditional and authoritarian. However, a key question in secularization theory is whether the development of more liberal values will drive individuals away from religious identification entirely or rather will liberalize religious institutions such that individual’s practices and beliefs are less directly tied to the dictums of the faith ==(PROBABLY SOME CITATIONS HERE)==. Therefore, in analyzing the effect of religiosity on values and attitudes, it is important to distinguish theological conservatism and literalism from a broader sense of religiosity that measures how important religion and religious practices are in a person’s life. 

==(NEED A SEGUE)== Classic modernization theory saw modernization as a fundamental process that would evolve similarly across countries, ultimately producing a global cosmopolitan society through the broad convergence in social and cultural systems [@fukuyama_end_1992]. Many scholars today criticize this view for privileging the historical experience of the West as a universal model. However, these scholars vary considerably in both the degree of heterogeneity they believe possible in processes of modernization as well as the larger moral implications of such heterogeneity. Some scholars continue to see industrialization and economic growth as drivers of cultural change toward liberal values, but mediated by cultural differences that will prevent convergence to a singular cosmopolitan norm [@inglehart_modernization_2000; @inglehart_modernization_2005]. On the other hand, “multiple modernities” scholars argue that while modernity will likely lead to changes in social and cultural systems, these changes will materialize in multiple dissimilar and non-convergent forms because countries develop within various historical and cultural contexts [@hefner_multiple_1998; @eisenstadt_multiple_2000; @kamali_multiple_2006; @bachika_cosmopolitanism_2011]. 

Huntington’s ==(CITE)== well known “Clash of Civilizations” thesis also emphasizes the incommensurate nature of cultural systems. According to Huntington, Western liberal traditions such as individualism, support for pluralism, and secularism should not be thought of as intrinsic to the process of modernity but rather a specific inheritance of the West [@huntington_clash_1996, pp. 69-72, 114]. Because modernity does not lead to cultural convergence, Huntington believed that economic development would only intensify cultural cleavage lines that distinguish civilizations, which he primarily identified along religious lines.

Huntington paid particular attention to Muslim populations and the rise of Islamic fundamentalism. In contrast with the research predominantly conducted in Western societies, @huntington_clash_1996 [pp. 112-113] argued that the primary agents for the contemporary rise of Islamic fundamentalism were an urban and educated middle class. Rapid economic growth and urbanization dislocate individuals from traditional structures of social support and this dislocation is experienced most intensely by upwardly mobile, young, urban, and educated individuals. 

# Analytical Approach and Theoretical Expectations

Using the Pew data detailed below, we develop a model that can simultaneously address the effects of education, religiosity, and development on support for violent practices and measure the heterogeneity in these effects across countries. Specifically, we use a random intercept and random slope multilevel model, in which the intercepts, the slope for the religiosity variable, and the slope for the educational attainment variable are allowed to vary across countries. Our general model specification is:

$$y_{ij}=\beta_{0j}+\beta_{1j}(\texttt{religiosity}_{ij})+\beta_{2j}(\texttt{education}_{ij})+\sum_{k=1}^K \lambda_kx_{ijk}+\epsilon_{ij}$$

where $y_{ij}$ is the score on the outcome measuring the support for violent practices for the $i$th respondent in the $j$th country. The intercept $\beta_{0j}$, and the two slopes of $\beta_{1j}$ and $\beta_{2j}$ on religiosity and education are allowed to vary by country. The model also includes $K$ additional independent control variables $x_{ijk}$ that are not allowed to vary by country. $\epsilon_{ij}$ is an individual-level error term. 

$\beta_{0j}$ measures the average support for support for violent practices in country $j$ and $\beta_{1j}$ and $\beta_{2j}$ measure the relationship between religiosity and education, respectively, and support for violent practices in country $j$. To complete the multilevel model structure, the three country-varying parameters have their own linear equations:

$$\beta_{0j}=\gamma_{01}+\gamma_{02}\texttt{development}_j+\delta_j$$
$$\beta_{1j}=\gamma_{11}+\gamma_{12}\texttt{development}_j+\eta_j$$
$$\beta_{2j}=\gamma_{21}+\gamma_{22}\texttt{development}_j+\tau_j$$




The structure shown here is for the fullest model in which we include a country-level measure of development (detailed below) that predicts the intercept and the two slopes. The $\gamma_{02}$ term measures the association of development with average support for violent practices in a country. The $\gamma_{12}$ and $\gamma_{22}$ terms measure how development in a country affects the individual-level relationship between support for violent practices and education/religiosity, respectively.

The three country level error terms $\delta_j$, $\eta_j$ and $\tau_j$ measure the country level random effects that measure country-level heterogeneity in terms of the intercept and two slopes. Because the correlation of these random effects is important for our understanding of this heterogeneity across countries, We place restrictions on the correlation in these error terms in the estimation of this model.

Given the model outlined above, we develop several expectations about the estimates it will produce. Importantly, these expectations operate on both the effects of religiosity and education pooled across countries and the variation in these effects across countries given by the random components. 

Classic modernization theory expects that the relationships between support for violent practices and religiosity should be positive, while the relationship between support for violent practices and education should be negative. Development should have a negative association with support for violent practices. Furthermore, since modernization both produces a secular and liberal educational system and weakens religious institutions, we would expect that countries with greater development should see more negative (or less positive) associations between education/religiosity and support for violent practices.

Among the critics of classic modernization theory, only Huntington offers a clear contrary expectation about the direction of these relationships. Huntington argued that the rise of contemporary Islamic fundamentalism was driven by an urban and educated middle class. Following this argument, we would expect education to be positively related to support for violent practices.

Importantly, the model used here allows us to analyze the correlation between the random components that capture country-level deviation from the global averages. This correlation can be informative. First, we will analyze how the country-level association between education/religiosity and support for violent practices is correlated to the average level of support for violent practices within a country. This relationship informs about the degree to which education and religious institutions move in step or contrary to popular attitudes and thus provides a test of the socialization hypothesis. Although the socialization hypothesis is specific to the effects of education, we can entertain a similar relationship for religiosity. For example, if the positive association between religiosity and support for violent practices diminishes in countries with lower overall support for violent practices, this would importantly imply that changes in value systems within the Muslim world are not dependent on strong secularization and a decline of religiosity, but rather that religiosity will respond to the prevailing norms of a society.

Second, we analyze the correlation between the effects of education and religiosity on support for violent practices across countries. We consider three possibilities in this regard. If the correlation is positive, then we see a process of synchronicity. In this case, when education has a strongly negative association with support for violent practices, we would expect to see a weaker positive, and perhaps even a negative association, between religiosity and support for violent practices. If this were the case, it would suggest that both educational and religious institutions are responding in the same liberalizing way to other societal influences.

If the correlation is negative, on the other hand, then we see a process of polarization between education and religious institutions. As the effect of one becomes stronger in one direction, the effect of the other variable becomes stronger in the other direction. Thus, educational attainment and religiosity exert two countervailing forces on value change. 

A third possibility is that the correlation is zero. This would suggest a situation of independence in which educational and religious institutions may change in disparate and unconnected ways that are not integrally tied to one another. This result would suggest greater heterogeneity in the process of value change at the country level. 

# Data and Measures

Data for this analysis come primarily from two cross-national surveys conducted by the Pew Research Center's Religion and Public Life project. The first survey (Tolerance and Tension: Islam and Christianity in Sub-Saharan Africa), conducted between 2008-2009 sampled more than 25,000 respondents in nineteen countries in sub-Saharan Africa. The second survey (The World's Muslims: Religion, Politics and Society), conducted between 2011-2012, sampled more than 30,000 respondents in twenty-six countries throughout the world with a specific focus on Muslim respondents. Most of the countries surveyed are Muslim-majority countries with a few exceptions (e.g. Russia, Thailand). The questionnaires for the surveys are very similar, although additional questions were added and some other questions were re-worded in the second survey. We focus our analysis only on questions that are consistent across the two surveys.

We combine Muslim respondents from these surveys together to construct our full analytical dataset. Five sub-Saharan African countries (Democratic Republic of Congo, Botswana, Rwanda, South Africa, and Zambia) were excluded from analysis because of minuscule (2% or less) Muslim populations. Four other countries were excluded because key questions for the analysis were not asked in those countries (Iran, Morocco, Mozambique, and Uzbekistan). Finally, Thailand was excluded because the sample was not nationally representative. Figure 1 shows a map of the countries included in our analysis with shading by the percent Muslim in each country.  The countries in the sample cover all regions of the world with substantial Muslim populations. In total, we use data from 35 countries and 35,400 respondents. The average sample size per country was 1,011 respondents with a minimum size of 245 respondents in Cameroon and a maximum size of 1,918 respondents in Bangladesh.

Because the country-level surveys were designed to be nationally representative, the data should be representative of within-country populations, but not necessarily the global Muslim population. Collectively, the countries in the sample roughly account for sixty-five percent of the global Muslim population [@pew_forum_on_religion_and_public_life_global_2012], but some important countries both symbolically (e.g. Saudi Arabia, Iran) and by population weight (e.g. India) are absent.

Several variables used in this analysis are constructs made up of multiple individual items, including the dependent variable and the measure of religiosity. All constructs were developed through an exploratory factor analysis that identified points of separation and correlation between items. A full report of this exploratory factor analysis is available in the supplementary materials.

## Measuring Support for Violent Practices

We develop our measures of support for violent practices based on multiple questions that were fielded in both surveys. Respondents were asked yes/no questions for whether they favored (a) the death penalty for people who leave Islam, (b) harsh punishments like whipping and cutting off hands for crimes like theft and robbery, and (c) stoning people who committed adultery. These three measures were highly correlated with one another (Cronbach's $\alpha=0.83$) and exploratory factor analysis indicated that a single scale worked well for all three variables. We also considered a likert-scale question with four ordinal categories on the justifiability of violence against civilians in defense of religion, but this variable had a much weaker correlation with the three other measures and so we dropped it from analysis.

Figure 2 shows the average level of support by country for the three items that make up our measure of support for violent practices. Countries tend to have similar levels of support for all items within the construct, but the variation across countries is substantial. Support for these values ranges from virtually no support in countries such as Azerbaijan and Kazakhstan to nearly universal support in countries such as Afghanistan and Egypt. Clearly, Islamic civilization does not produce a uniform set of values on these issues.

We constructed the dependent variable for our models by counting the number of favorable responses to each question and then re-scaling this tally to have a mean of zero and a standard deviation of one.

## Measuring Development

==TODO==

## Independent Variables

Education is a key measure in our analysis, but the categories used for educational attainment are country-specific, making it challenging to include in a cross-national analysis. Educational attainment was reported as a three-category system for the sub-Saharan African countries and relative to country-specific educational systems for the remaining countries.^[the country-specific systems ranged from a high of twelve distinct categories to a low of five distinct categories.] We harmonize these measures by creating a quantile score based on the distribution of the educational attainment variable within each country. Each respondent was assigned a midpoint value on the quantile score between their given level of education and the next lowest level (or zero when the respondent was in the lowest category). This quantile score measures a respondent’s relative position on the distribution of education within a country.^[We also considered a three-category measure of absolute educational attainment consisting of no secondary education, at least some secondary education, and post-secondary education that could be used for all countries. Sensitivity tests showed that these models produced similar results, but the BIC model fit statistics strongly preferred the educational quantile measure. Full results are available in the supplementary materials.]

We measure each respondent’s religiosity using a concept that combines the experiential and ritualistic dimensions of Glock and Stark's [-@glock_religion_1965] framework. Our goal is to isolate the importance of religion in a person’s daily life as measured by their personal experience and practice of it from specific ideological beliefs and knowledge about the religion. We measure religiosity with a three-item construct including a question on the importance of religion in a person’s life, the frequency of mosque attendance, and the frequency of prayer. Across the entire sample, this three item construct had a Cronbach’s $\alpha$ of 0.68.^[Mosque attendance has been criticized by some scholars as an inappropriate Western import for measuring religiosity among Muslims [@el-menouar_five_2014]. However, sensitivity tests suggested that mosque attendance had similar effects on outcomes as other measures of religiosity and we therefore retain it. These results are available in the supplementary materials.]

Glock and Stark’s framework contains three other dimensions: ideological, intellectual, and consequential that tap into respondent’s theological knowledge and values. However, for our purposes, such an approach is problematic. Individuals with more literalist and theologically conservative beliefs are likely to have more anti-liberal values simply because some of the measures used for the dependent variable can be argued to have scriptural justification. To isolate the effect of religiosity from such theological conservatism, we tested a separate construct that measured theological conservatism and literalism in a person’s actual beliefs. We considered questions on whether a person must believe in god to be moral, whether Islam is the one true faith, and whether there was only one way to interpret religious teachings. However, these questions did not hold up well as a single construct (Cronbach’s $\alpha=0.38$). Therefore, to capture theologically conservative beliefs and practices, we included all three questions as separate independent variables in our models.

We include a variety of other individual-level variables in all models. We include variables for the age (five-year brackets), gender, and urbanicity of the respondent. Income was reported in different brackets for each country and so we use a method identical to that for education to create income quantile scores.^[Income was reported in loosely defined quartiles (i.e. four categories from “low” to “high”) for the sub-Saharan African countries and brackets that were specific to each national currency for remaining countries. The country-specific income brackets ranged from a high of seventeen distinct categories to a low of five distinct brackets.]

We also include a measure of the respondent’s self-reported denomination. The primary division here is between Sunni and Shia, but many respondents also identified in a non-denominational way (e.g. “just a Muslim”) which we retain as a separate category. We combine all other denominations into a single “other” category. A separate item asked respondents whether they identified with any Sufi orders. We code this as a binary variable that is distinct from the denominational categories.

We also control for non-religious ideological views. We constructed an index of socially conservative views based on the respondent’s answers regarding the acceptability of seven stigmatized behaviors (drinking alcohol, euthanasia, suicide, abortion, prostitution, premarital sex, and homosexuality; Cronbach’s $\alpha=0.76$). We also combine two questions that gauge respondents’ attitudes toward Western movies, music, and television as an anti-Westernization scale. Finally, we include questions on whether religion is in conflict with modernity, and whether the country would be better off with a strong leader rather than a democratic government.

## Multiple Imputation

We use multiple imputation to address missing values in the dataset. We imputed five complete datasets using multivariate imputation by chained equations [@buuren_mice_2011]. We generally did not impute values when a question was missing because it was not asked in a particular country, but we made two exceptions to this rule. Questions regarding the moral acceptability of prostitution, premarital sex, and homosexuality were not asked in Afghanistan and the two questions about the morality of western movies, music, and television were not asked in Lebanon. In both of these cases we imputed values in order to maximize country sample size. The percentage of values imputed ranged from a high of 11.4% for the question on whether religion was in conflict with modernity to 0.7% for the respondent’s age. We included dependent variables in the imputation procedure, but do not impute missing values for these variables.

## Scaling Variables

To facilitate comparisons between variables in the models, all quantitative variables have been re-centered on the mean and re-scaled. Dependent variables have been divided by their standard deviation. Independent variables have been divided by twice their standard deviation.  The estimated effects of quantitative variables shown throughout this article can be interpreted as the expected change in standard deviations of the dependent variable for an increase of two standard deviations in the independent variable. Dividing by twice the standard deviation makes the slopes of quantitative variables in regression models roughly comparable to the effects of categorical dummy variables [@gelman_scaling_2008].

# Results

Table 1 shows the results of three multilevel models predicting support for violent practices. Model 1 includes only individual level variables. Model 2 adds in the country-level Human Development Indicator (HDI) as a predictor of average support for violent practices in a country. Model 3 additionally allows HDI to be a predictor of the association between religiosity/education and support for violent practices within a country. All variables have been scaled for comparability of effects.

The individual-level variables are highly consistent across models. Although we focus primarily on the effects of education and religiosity, we first briefly summarize the effects of other variables on support for violent practices. Income has little effect on support for violent practices. Similarly, we observe no difference between men and women in support for violent practices. Age differences are relatively small and do not demonstrate a consistent trend when comparing younger to older respondents. Rather, the results suggest specific cohort effects where the age groups between 35-44 and age 50-59 are the least likely to be supportive of violent practices. Urban residents are less likely to support violent practices than those in rural areas. In terms of denomination, Sunnis were the most supportive of violent practices and Shias the least supportive, with other denominations and “just a Muslim” respondents falling in between. Self-identifying as a member of a Sufi order was associated with greater support for violent practices. All of the variables measuring theological conservatism were positively associated with support for violent practices. The strongest effect was for respondents who said that Islam is the one true faith. Respondents with more anti-Western views were also more supportive of violent practices. Preferences for democracy and social conservatism had little association with support for violent practices.

Among the individual-level variables, religiosity has the strongest association with support for violent practices. A two standard deviation increase in religiosity is associated with roughly a 0.24 standard deviation increase in the support for violent practices scale, even when holding constant a variety of demographic and ideational variables. On average, across countries, Muslims who are more religiously observant and devout are more likely to support violent practices and this result is not simply a function of theological conservatism, social conservatism, or anti-Western sentiment. 


The education quantile measure has a smaller negative association with support for violent practices. A two standard deviation increase in education quantile is associated with a 0.062 standard deviation reduction in the support for violent practices scale.

Model 2 introduces the HDI measure as a predictor of support for violent practices. This country-level predictor has the largest association of any term in the model. A two standard deviation increase in the HDI is associated with a 0.417 standard deviation decrease in the average support for violent practices scale in a country. Again, we find results that are broadly consistent with modernization theory. Individuals from more developed countries are much less supportive of violent practices, on average.

Model 3, however, overturns some of the expectations of modernization theory. In this model, we allow for an interaction between HDI and our measures of religiosity and education. Effectively, we are allowing the association between religiosity/education and support for violent practices to vary by the level of HDI. Our expectation was that these associations would be negative, indicating that, in more developed countries, the association with support for violent practices is more negative for education and less positive for religiosity. However, we find the opposite. Both point estimates are positive, although the effect for religiosity is small and not statistically significant. The education effect, however, is quite substantial. The results here indicate that the negative association between education and support for violent practices is *weaker*  and more likely to reverse direction to a positive association in more developed countries. 

We further explore this puzzling finding in Figure 3. This figure plots the country-level random intercepts from Model 1 by the HDI for each country. These country-level intercepts give the average support for violent practices in a country after accounting for individual-level variables.  Consistent with the results for Model 3, the association is clearly negative. Both Egypt and Tunisia are outliers in the strength of the education effect, although in opposite directions, but neither appears to be exerting undue influence on the association observed here. It is notable that the negative association seems to be somewhat driven by the sub-Saharan African countries which have relatively low scores on HDI but sizable negative associations for the effect of education. To explore how regional variation might affect the results, we have plotted separate best-fitting lines for the sub-Saharan African countries and the remaining countries. The results do suggest a weaker association for the remaining countries. However, we hesitate to chalk this association up to unobserved regional and culture differences across countries. First, we still observe the negative association within the subset of sub-Saharan African countries, and the difference in slopes estimated here is not itself statistically significant ==(TEST THIS)==. Second, while causal implications of observational data are always tenuous, the regional division here doesn’t necessarily invalidate the first-order point ==THIS IS VERY OPAQUE==.

The associations described above are the averages across countries in our sample. Because we allowed these associations to vary by country, we can look more closely at this country-level heterogeneity. The standard deviation of these country effects is shown at the bottom of Table 1 and indicates substantial variation. There is slightly more country-level variation in the association between religiosity and support for violent practices than in the association between education and support for violent practices. However, because the standard deviation of the education effect is roughly twice the size of the average effect, the results here suggest that the education effect is actually reversed in some countries.

Figure 4 shows the religiosity and education slopes for all countries as estimated in Model 3 of Table 1. As the figure shows, six countries (Egypt, Algeria, Afghanistan, Malaysia, Kenya, Pakistan, and Liberia) have estimated slopes that indicate a positive association between educational quantile and support for violent practices. The effects are very close to zero for Pakistan and Liberia, but substantial for the other countries. In these countries, individuals with more education tend to be more supportive of violent practices. Significant variation exists among countries with negative slopes as well. Tunisia stands out as an outlier in the negative direction with a slope that is nearly double the size of its nearest neighbor, Ghana. 

On the other hand, all of the estimated slopes for religiosity are consistently positive, with the exception of Azerbaijan where religiosity has no association with support for violent practices. While the variation in these positive effects is substantial, the results suggest that a reversal of direction for the religiosity effect is unlikely. 

We now turn to a more detailed examination of the relationship between the random components in the models. Table 1 shows the correlation between these components. We can see that both slopes are positively related to the intercept. The correlation is higher for religiosity than for education. However, the education correlation is much stronger after including HDI in Model 2 ==(DOES THIS TELL US SOMETHING?)==. 

To explore these correlations in more detail, Figure 5 shows the relationship between the country-specific intercepts and the country-specific slopes for religiosity and education. As the correlation indicates, there is a strong positive correlation in both cases. In countries with less support for violent practices overall, the association between education and support for violent practices tends to be more negative and the association between religiosity and support for violent practices tends to be less positive. The correlation here suggests a substantial socialization effect on both religious and educational institutions. Prevailing attitudes within a society affect the liberalizing and conservatizing effects of educational and religious institutions.

Finally, we look at the relationship between the two measures of association. Do the effects of religiosity and education within a country tend to work in synchronicity or are they polarized? As Table 1 shows, the correlation between the two measures of association is very low, albeit slightly positive. Figure 6 shows the relationship between the two slopes on a scatterplot, confirming the low correlation. In short, there does not seem to be any connection between educational and religious divisions within a country on this outcome measure. For example, Tunisia and Egypt have similar associations between religiosity and support for violent practices, but radically different associations between education and support for violent practices. Tunisia has by the far most negative association of any country while Egypt has the most positive. The results here suggest that while religiosity and education have somewhat predictable effects on support for violent practices, the particular constellation of these two effects varies in non-predictable ways across countries. 

# Conclusions

The average effects of education and religiosity are as expected from prior work and expectations of modernization theory, but the effects of religiosity are much stronger.

The religiosity effects are not a surrogate for theological literalism -- the “duh” argument. We control for theological conservatism/literalism in the models. More importantly, while the average effects of religiosity are strongly positive, the results by country are highly variable. In some countries, there is virtually no correlation between religiosity and support for violent practices. Islamic conservatism is not destiny, but its also not irrelevant. 

There is some evidence in support of the socialization hypothesis. Both education and religiosity had more positive/less negative association with support for violent practices in countries that were more supportive of these practices overall. The finding for education is expected, but the correlation is actually much stronger for religiosity. This suggests that religious institutions may also be socialized to the norms of society. 
Somewhat surprisingly, there is very little correlation in the effects of religiosity and education across countries. This implies that there is not necessarily a greater singular force (e.g. “modernization”) driving change in both religious and educational institutions, but rather that these two institutions are affected disparately by factors unique to each country. 



