---
output:
  pdf_document:
    fig_caption: yes
    template: ./resources/aog-latex-ms.tex
fontfamily: mathpazo
fontsize: 11pt
---

```{r setup, echo=FALSE, warning=FALSE, error=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, error = FALSE, warning = FALSE)
library(here)
source(here("analysis","useful_functions.R"))
source(here("analysis","check_packages.R"))
load(here("analysis","output","analytic_samples.RData"))
load(here("analysis","output","country_data.RData"))
```

```{r run_models}
formula_individual <- formula(violence~(1+religiosity+educqq_scl|country)+
                                religiosity+educqq_scl+incomeqq_scl+
                                age25_29+age30_34+age35_39+age40_44+
                                age45_49+age50_54+age55_59+ageAge60orover+
                                Female+Urban+
                                Shia+Other+Nothinginparticular+sufi_ctr+
                                NecessarytobelieveinGodtobemoral+
                                islam_truth_ctr+islam_oneway_ctr+
                                conflict_modern_ctr+anti_western+
                                anti_democratic_ctr+social_cons)
formula_hdi_intercept <- update(formula_individual, .~.+hdi_scaled)
formula_hdi_full <- update(formula_individual, .~.+(religiosity+educqq_scl)*hdi_scaled)

results_individual <- pool_re_models(mclapply(analytic_samples, function(x) {
  lmer.converge(formula_individual, data=x)
}))
results_hdi_intercept <- pool_re_models(mclapply(analytic_samples, function(x) {
  lmer.converge(formula_hdi_intercept, data=x)
}))
results_hdi_full <- pool_re_models(mclapply(analytic_samples, function(x) {
  lmer.converge(formula_hdi_full, data=x)
}))
```

# Tables and Figures


```{r model-table, results='asis'}
#the function for converting back for knitreg from pooled model results
convert_model_re <- function(model) {
  tr <- createTexreg(
    coef.names = names(model$fixef$beta), 
    coef = model$fixef$beta, 
    se = model$fixef$se, 
    pvalues = model$fixef$pvalue,
    gof.names = c("N (individual)","N (country)", "BIC",
                  "SD (religiosity)","SD (education quantile)",
                  "r(intercept, religiosity)","r(intercept, education)",
                  "r(religiosity, education)"),
    gof = c(model$sumStats$n, model$sumStats$ngrp, model$sumStats$BIC,
            model$ranef_sd["religiosity"], model$ranef_sd["educqq_scl"],
            model$ranef_cor["(Intercept)","religiosity"],
            model$ranef_cor["(Intercept)","educqq_scl"],
            model$ranef_cor["religiosity","educqq_scl"]), 
    gof.decimal = c(F,F,F,T,T,T,T,T)
  )
}


knitreg(lapply(list(results_individual, results_hdi_intercept, results_hdi_full),
               convert_model_re),
        digits=3,
        custom.coef.names=c("Intercept","Religiosity","Education quantile",
                            "Income quantile","Age 25-29","Age 30-34","Age 35-39",
                            "Age 40-44","Age 45-49","Age 50-54","Age 55-59",
                            "Age 60 and over", "Female", "Urban", "Shia",
                            "Other denomination","Just a Muslim", "Sufi",
                            "Believe in god to be moral",
                            "Islam is the one true faith",
                            "One way to interpret relig. teachings",
                            "Religion in conflict with modernity",
                            "Anti-Westernization scale",
                            "Prefers strong leader to democracy",
                            "Socially conservative scale",
                            "Human development index (HDI)",
                            "HDI x religiosity", 
                            "HDI x education quantile"),
        single.row=TRUE,
        dcolumn=TRUE,
        caption="Results from multilevel models predicting support for violent practices for violating norms among Muslims.",
        caption.above=TRUE,
        custom.note="\\parbox{\\linewidth}{\\vspace{2pt} \\small %stars \\\\ \\emph{Notes:} All models include random country-level intercepts and slopes for some variables. All quantitative variables are divided by twice their standard deviation for comparability. Results are based on five complete datasets with imputation for missing values.}")
```

```{r build-country-effects, echo=FALSE}
country_effects <- as_tibble(results_hdi_full$country_effects)
colnames(country_effects)[1] <- "intercept"
country_effects$country <- rownames(results_hdi_full$country_effects)
temp <- as_tibble(results_individual$country_effects)
colnames(temp)[1] <- "intercept"
temp$country <- rownames(results_individual$country_effects)
temp <- subset(temp, select=c("intercept","religiosity","educqq_scl"))
colnames(temp) <- c("intercept_ind","religiosity_ind","educqq_ind")
country_effects <- cbind(country_effects, temp)
temp <- subset(analytic_samples[[1]], !duplicated(country),
               select=c("country","hdi"))
country_effects <- merge(country_effects, temp)
country_effects <- as_tibble(country_effects)
```


```{r country_averages, fig.cap="Dotplot of percentage of Muslim respondents who support three different questions measuring support for violent practices for the violation of norms. Countries are ordered from lowest to highest average level of support across all three questions."}
country_agg <- 100*with(analytic_samples[[1]],
     cbind(death_apostasy=tapply(death_apostasy=="Favor",country,mean,na.rm=TRUE),
           stone_adultery=tapply(stone_adultery=="Favor",country,mean,na.rm=TRUE),
           severe_corporal=tapply(severe_corporal=="Favor",country,mean,na.rm=TRUE)))
country.scores <- sort(apply(country_agg,1,mean, na.rm=TRUE))
temp <- as.data.frame.table(country_agg)

colnames(temp) <- c("country","variable","percent")
temp$country <- factor(temp$country,
                       levels=names(country.scores),
                       labels=shortenCountryNames(names(country.scores)))
ncountry <- length(unique(temp$country))
temp$variable <- factor(temp$variable,
                        levels=c("death_apostasy","severe_corporal","stone_adultery"),
                        labels=c("Death for apostasy",
                                 "Severe corporal punishment",
                                 "Adulterers should be stoned"))
ggplot(temp, aes(x=country, y=percent,group=variable))+
  geom_point(aes(colour=variable, shape=variable))+coord_flip()+
  #scale_colour_brewer(palette = "Dark2", name="Value")+
  scale_color_viridis_d(name="Variable", end=0.75)+
  scale_shape_manual(values=c(15,16,17,7,9,10), name="Variable")+
  ylab("Percentage in support")+
  xlab("")+
  ylim(0,100)+
  theme_bw()
```

```{r figure_world_map, fig.cap="Map showing countries included in the analysis by percent Muslim. Mollweide projection used to preserve area proportions."}
proj_chosen <- "mollweide"
map.world <- map_data("world", projection=proj_chosen, xlim=c(-15,160), ylim=c(-43,90))
#get rid of greenland for map niceness
map.world <- subset(map.world, region!="Greenland")

#merge in country data to get percent Muslim
#change a couple of names to match world map
country_data$country <- as.character(country_data$country)
country_data$country[country_data$country=="Palestinian Territories"] <- "Palestine"
country_data$country[country_data$country=="Guinea Bissau"] <- "Guinea-Bissau"
country_data$country <- as.factor(country_data$country)
map.world <- merge(map.world, country_data, by.x="region", by.y="country", all.x=TRUE, all.y=FALSE)
map.world <- map.world[order(map.world$order),]
map.world$pct_muslim_cat <- cut(map.world$pct_muslim, breaks=c(0,25,50,75,100),
                                right=FALSE,
                                labels=c("0-24%","25-49%","50-74%","75-100%"))

#calculate centroids for plotting names
country_names <- aggregate(cbind(long, lat)~region, 
                           data=subset(map.world, !is.na(pct_muslim_cat)), FUN=mean)

ggplot(map.world, aes(x=long, y=lat))+
  geom_polygon(aes(group=group, fill=pct_muslim), 
               col="grey80", size=0.1)+
  geom_text_repel(data=country_names, aes(label=shortenCountryNames(region)), 
            col="black", size=1.75, force=1, 
            segment.colour = "grey20", arrow = arrow(length=unit(0.05, "lines")))+
  # scale_fill_manual(values=c("#c2e699",
  #                            "#78c679",
  #                            "#31a354",
  #                            "#006837"),
  #                   na.value = "grey90",
  #                   name="Percent Muslim",
  #                   labels=c(levels(map.world$pct_muslim_cat), "Not in sample"))+
  scale_fill_viridis_c(begin=0.25, direction = -1)+
  theme(panel.background = element_rect(fill = "white"),
        plot.background = element_rect(fill = "white"),
        panel.grid = element_blank(),
        axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "right")
```

```{r intercept-slope-plot, fig.cap="A caption"}
temp <- subset(country_effects, 
               select=c("country","intercept","religiosity"))
temp$variable <- "religiosity"
temp2 <- subset(country_effects, 
               select=c("country","intercept","educqq_scl"))
temp2$variable <- "education"
colnames(temp) <- colnames(temp2) <- c("country","intercept","slope","variable")
temp <- rbind(temp, temp2)
ggplot(temp, aes(x=intercept, 
                            y=slope))+
  geom_hline(yintercept=0, linetype=2)+
  geom_point()+
  geom_smooth(method="lm", se=FALSE)+
  geom_text_repel(aes(label=country), size=2)+
  facet_wrap(~variable)+
  labs(x="average support for violent practices in country (intercept)", y="association (slope) between education/religiosity and\nsupport for violent practices in country")+
  theme_bw()
```


```{r slope-compare-plot, fig.cap="A caption"}
ggplot(country_effects, aes(x=religiosity, 
                            y=educqq_scl))+
  geom_hline(yintercept=0, linetype=2)+
  geom_point()+
  geom_smooth(method="lm", se=FALSE)+
  geom_text_repel(aes(label=country), size=3)+
  labs(x="religiosity slope in country", y="education slope in country")+
  theme_bw()
```

```{r hdi-effect, fig.cap="A caption" }
ggplot(country_effects, aes(x=hdi, y=educqq_ind))+
  geom_point()+
  geom_smooth(method="lm", se=FALSE)+
  geom_text_repel(aes(label=country), size=3)+
  labs(x="human development index",
       y="education slope in country based on individual-level model")+
  theme_bw()
```